### ISSUE TITLE
Support additional Notion Blocks - Table, Toggle List and Todo

### ISSUE THREAD

**Issue by tewnut** [nartc/notion-stuff#15]
In the package @notion-stuff/blocks-html-parser, the following blocks are not available yet:
- [ ] Table: Just not appear
- [ ] Toggle List: missing the children blocks
- [ ] Todo: shown without any html tags
